---
# vars file for host_config
admin_user: #MUST BE SAME AS USER FROM DEPLOYMENT PLAYBOOK
book_title: #"Be Kind To One Another"
book_text_url: #"http://gutenberg.org/cache/epub/63261/pg63261.txt"
book_image_url: #"https://www.gutenberg.org/cache/epub/63261/pg63261.cover.medium.jpg"
